### ISSUE TITLE
No Reward RL

### ISSUE THREAD

**Issue by wenkesj** [unixpickle/metaverse#1]
> I fear that there will be a great amount of overfitting. There are only ~100 games in Universe with reward signals. If I want more data, I may have to find a way to use the games without reward signals.
>
> I also suspect that TRPO will fail for some of the games in Universe. It is possible that transfer learning will actually help learn those games, but I am not super optimistic.
Have you thought about

You might like [this paper](https://pathak22.github.io/noreward-rl/resources/icml17.pdf) on self-supervision and curiosity learning. I don't doubt you've seen it yet, but as a possible TRPO comparison and alternative.

**Comment by unixpickle** [comment]
Will have a look at that paper. I'd rather use human examples for no-reward games, but that could be extremely time consuming. Self-supervision might be a good compromise.
